### ISSUE TITLE
Bicep deployment throws "Workload Profile property is not supported" when deploying Container App Environment

### ISSUE THREAD

**Issue by ndamulelonemakh** [Azure/bicep-types-az#2394]
**Bicep version**
run `bicep --version` via the Bicep CLI, `az bicep version` via the AZ CLI or via VS code by navigating to the extensions tab and searching for Bicep

`Bicep CLI version 0.31.92 (b06509316a)`

```json
{
  "azure-cli": "2.67.0",
  "azure-cli-core": "2.67.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "containerapp": "1.1.0b1",
    "ml": "2.32.4",
    "ssh": "2.0.6"
  }
}
```

**Describe the bug**
A clear and concise description of what the bug is vs what you expected to happen

Trying to deploy a container app environment with a workload profile enabled, does not work. Despite changing to the latest API version, I get the error:

"Workload Profile property is not supported"

**To Reproduce**

```yaml
@description('The resource name for the container app environment')
param containerAppEnvName string = 'mybugcaeeastus01'

@description('The Log Analytics workspace to send logs to')
param logAnalyticsWorkspaceName string = 'log-mybugcaeeastus01'

@description('The primary region to deploy the container app to')
param location string = 'eastus'

@description('The tags to assign to all resources created by this template')
param tags object = {}

resource log 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: logAnalyticsWorkspaceName
  location: location
  properties: {
    sku: {
      name: 'PerGB2018'
    }
  }
}

resource cae 'Microsoft.App/managedEnvironments@2024-03-01' = {
  name: containerAppEnvName
  location: location
  tags: tags
  properties: {
    zoneRedundant: false
    workloadProfiles: [
      {
        name: 'Consumption'
        workloadProfileType: 'Consumption'
        minimumCount: 1
        maximumCount: 1
      }
    ]
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: log.properties.customerId
        sharedKey: log.listkeys().primarySharedKey
      }
    }
  }
}
```

- az group create -n bug-test-rg
- az deployment group create --template-file bug.bicep -g bug-test0rg 

**Additional context**

```json
{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/<my-sub>/resourceGroups/<my-rg>/providers/Microsoft.Resources/deployments/main","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidTemplateDeployment","message":"The template deployment 'containerAppEnvironmentDeployment' is not valid according to the validation procedure. The tracking id is '1a534671-4f81-41a1-98b9-e5a8d3e9f3f3'. See inner errors for details.","details":[{"code":"ValidationForResourceFailed","message":"Validation failed for a resource. Check 'Error.Details[0]' for more information.","details":[{"code":"WorkloadProfilePropertyNotSupported","message":"Workload Profile property is not supported"}]}]}]}}
```
